config/routes.rb
NfeSws::Application.routes.draw do

  resources :crons do
    collection do
      post :search, to: 'crons#index'
      get 'download_xml_retorno'
    end
  end

  resources :usuario_empresas

  devise_for :users

  resources :control_users, only: [:index, :edit, :update, :show, :destroy], as: :users

  resources :empresas do
    collection { post :search, to: 'empresas#index' }
  end

  resources :dominio_campos do
    collection { post :search, to: 'dominio_campos#index' }
  end

  resources :dominio_valores do
    collection { post :search, to: 'dominio_valores#index' }
  end

  resources :dominios do
    collection { post :search, to: 'dominios#index' }
  end

  resources :nota_duplicatas do
    collection { post :search, to: 'nota_duplicatas#index' }
  end

  resources :nota_produtos do
    collection { post :search, to: 'nota_produtos#index' }
  end

  resources :nota_fiscais do
    collection do
      post :search, to: 'nota_fiscais#index'
      post 'manifestacao_destinatario'
      get 'download_xml_nfe_sefaz'
      get 'download_xml_nfe'
      get 'download_danfe_nfe'
      post 'negar_nfe'
      get :report, to: 'nota_fiscais#report_notas_fiscais'
      post :report, to: 'nota_fiscais#report_notas_fiscais'
      post :importar_nfe_xml, to: 'nota_fiscais#importar_nfe_xml'
      get :citacoes, to: 'nota_fiscais#citacoes'
      get :search_citacoes, to: 'nota_fiscais#citacoes'
      post :download_nfe_terceiro, to: 'nota_fiscais#download_nfe_terceiro'
    end
  end

  get "home/index"
  get "home/minor"

  root to: 'home#index'

end

app/models/dominio_campo.rb
class DominioCampo < ActiveRecord::Base
  belongs_to :dominio

  validates :descricao, presence: true

end

app/controllers/dominio_campos_controller.rb
class DominioCamposController < ApplicationController
  before_action :set_dominio_campo, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /dominio_campos
  # GET /dominio_campos.json
  def index
    @search = DominioCampo.search(params[:q])
    if params[:q].nil?
      #  @nota_fiscais = NotaFiscal.order("dtEmissaoNfe").limit(10)
      @dominio_campos = DominioCampo.order("id")
     else
      @dominio_campos = @search.result
    end
    @search.build_condition if @search.conditions.empty?
    @search.build_sort if @search.sorts.empty?
  end


  # GET /dominio_campos/1
  # GET /dominio_campos/1.json
  def show
  end

  # GET /dominio_campos/new
  def new
    @dominio_campo = DominioCampo.new
  end

  # GET /dominio_campos/1/edit
  def edit
  end

  # POST /dominio_campos
  # POST /dominio_campos.json
  def create
    @dominio_campo = DominioCampo.new(dominio_campo_params)

    respond_to do |format|
      if @dominio_campo.save
        format.html { redirect_to @dominio_campo, notice: 'Dominio campo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @dominio_campo }
      else
        format.html { render action: 'new' }
        format.json { render json: @dominio_campo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dominio_campos/1
  # PATCH/PUT /dominio_campos/1.json
  def update
    respond_to do |format|
      if @dominio_campo.update(dominio_campo_params)
        format.html { redirect_to @dominio_campo, notice: 'Dominio campo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @dominio_campo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dominio_campos/1
  # DELETE /dominio_campos/1.json
  def destroy
    @dominio_campo.destroy
    respond_to do |format|
      format.html { redirect_to dominio_campos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dominio_campo
      @dominio_campo = DominioCampo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dominio_campo_params
      params.require(:dominio_campo).permit(:descricao, :dominio_id)
    end
end

app/helpers/dominio_campos_helper.rb
module DominioCamposHelper
end

app/views/dominio_campos/_condition_fields.html.erb
<div class="field">
  <%= f.attribute_fields do |a| %>
    <%= a.attribute_select associations: [:category] %>
  <% end %>
  <!-- <%= f.predicate_select %> -->
  <%= f.predicate_select only:[:gteq,:lteq,:eq,:cont]%>
  <%= f.value_fields do |v| %>
    <%= v.text_field :value %>
  <% end %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</div>

app/views/dominio_campos/_form.html.erb
<%= form_for(@dominio_campo) do |f| %>
  <% if @dominio_campo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dominio_campo.errors.count, "error") %> prohibited this dominio_campo from being saved:</h2>

      <ul>
      <% @dominio_campo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descricao %><br>
    <%= f.text_field :descricao %>
  </div>
  <div class="field">
    <%= f.label :dominio_id %><br>
    <%= f.text_field :dominio_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dominio_campos/edit.html.erb
<%- model_class = DominioCampo -%>
<h1>Editar DominioCampo</h1>
<%= render 'form' %>

app/views/dominio_campos/index.html.erb
<%- model_class = DominioCampo -%>
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>dominio_campos</h2>
        <ol class="breadcrumb">
            <li><a href="<%= url_for :controller => 'home', :action => 'index' %>">Home</a></li>
            <li class="active"><strong>dominio_campos</strong></li>
        </ol>
    </div>
    <div class="col-lg-2"></div>
</div>
<p id="notice"><%= notice %></p>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <%= link_to new_dominio_campo_path, class: 'btn btn-primary btn-xs' do %>
                        <span class="glyphicon glyphicon-plus"></span>
                        Novo
                    <% end %>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a href="#modal-form" data-toggle="modal" class="fa fa-wrench" ></a>

                        <div class="modal inmodal" id="modal-form" tabindex="-1" role="dialog" aria-hidden="true">
                            <div class="modal-dialog">
                                <%= search_form_for @search, url: search_dominio_campos_path, method: :post do |f| %>
                                <div class="modal-content animated bounceInRight">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                        <h4 class="modal-title">Pesquisa</h4>
                                    </div>
                                    <div class="modal-body">
                                        <%= f.condition_fields do |c| %>
                                            <%= render "condition_fields", f: c %>
                                        <% end %>
                                        <p><%= link_to_add_fields "Adicionar condições", f, :condition %></p>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Fechar</button>
                                        <%= f.submit "Procurar", class: "btn btn-primary" %>
                                    </div>
                                </div>
                                <% end %>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="ibox-content">
                    <table class="table table-striped table-bordered table-hover Tabela" >
                        <thead>
                            <tr>
                                <th width="05%">&nbsp</th>
                                <th width="05%">&nbsp</th>
                                <th width="05%">&nbsp</th>
                                                                <th>Descricao</th>
                                                                <th>Dominio</th>
                                                            </tr>
                        </thead>
                        <tbody>
                            <%= content_tag_for(:tr, @dominio_campos) do |dominio_campo| %>
                            <td><%= link_to '', dominio_campo, class: "btn btn-xs fa fa-search"%></td>
                            <td><%= link_to '', edit_dominio_campo_path(dominio_campo), class: "btn btn-xs fa fa-paste" %></td>
                            <td><%= link_to '', dominio_campo, class: "btn btn-xs fa fa-times", method: :delete, data: { confirm: 'Confirma Exclusão ?' } %></td>
                                                        <td><%= dominio_campo.descricao %></td>
                                                        <td><%= dominio_campo.dominio_id %></td>
                                                        <% end %>
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>&nbsp</th>
                                <th>&nbsp</th>
                                <th>&nbsp</th>
                                                                <th>Descricao</th>
                                                                <th>Dominio</th>
                                                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<% content_for :javascript do %>
<script type="text/javascript">
    $(function() {

      $('.Tabela').dataTable({
        "dom": 'T<"clear">lfrtip',
        "aoColumnDefs": [
              { 'bSortable': false, 'aTargets': [ 0,1,2 ] }
           ],
        "tableTools": {
            "sSwfPath": "../assets/dataTables/swf/copy_csv_xls_pdf.swf"
        }
    });
  });
</script>

<% end %>

app/views/dominio_campos/new.html.erb
<%- model_class = DominioCampo -%>
<h1>Novo DominioCampo</h1>
<%= render 'form' %>

app/views/dominio_campos/show.html.erb
<%- model_class = DominioCampo -%>
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-content">
                <p id="notice"><%= notice %></p>
                <form class="form-horizontal">
                    <div class="form-group">
                        <div class="col-md-2 control-label">
                             <%= model_class.human_attribute_name(:descricao) %>:
                        </div>
                        <div class="col-md-10">
                            <label class="form-control">
                                <%= @dominio_campo.descricao %>
                            </label>
                        </div>
                    </div>
                    <div class="hr-line-dashed"></div>

                                    <div class="form-group">
                        <div class="col-md-2 control-label">
                             <%= model_class.human_attribute_name(:dominio) %>:
                        </div>
                        <div class="col-md-10">
                            <label class="form-control">
                                <%= @dominio_campo.dominio_id %>
                            </label>
                        </div>
                    </div>
                    <div class="hr-line-dashed"></div>

                                <div class="form-group">
                    <div class="col-sm-4">
                        <%= link_to edit_dominio_campo_path(@dominio_campo), class: 'btn btn-primary' do %>
                        Editar
                        <% end %>
                        <%= link_to 'Voltar', dominio_campos_path, :class => 'btn btn-white' %>
                    </div>
                </div>

                </form>

            </div>
        </div>
    </div>
</div>