config/routes.rb
NfeSws::Application.routes.draw do

  resources :crons do
    collection do
      post :search, to: 'crons#index'
      get 'download_xml_retorno'
    end
  end

  resources :usuario_empresas

  devise_for :users

  resources :control_users, only: [:index, :edit, :update, :show, :destroy], as: :users

  resources :empresas do
    collection { post :search, to: 'empresas#index' }
  end

  resources :dominio_campos do
    collection { post :search, to: 'dominio_campos#index' }
  end

  resources :dominio_valores do
    collection { post :search, to: 'dominio_valores#index' }
  end

  resources :dominios do
    collection { post :search, to: 'dominios#index' }
  end

  resources :nota_duplicatas do
    collection { post :search, to: 'nota_duplicatas#index' }
  end

  resources :nota_produtos do
    collection { post :search, to: 'nota_produtos#index' }
  end

  resources :nota_fiscais do
    collection do
      post :search, to: 'nota_fiscais#index'
      post 'manifestacao_destinatario'
      get 'download_xml_nfe_sefaz'
      get 'download_xml_nfe'
      get 'download_danfe_nfe'
      post 'negar_nfe'
      get :report, to: 'nota_fiscais#report_notas_fiscais'
      post :report, to: 'nota_fiscais#report_notas_fiscais'
      post :importar_nfe_xml, to: 'nota_fiscais#importar_nfe_xml'
      get :citacoes, to: 'nota_fiscais#citacoes'
      get :search_citacoes, to: 'nota_fiscais#citacoes'
      post :download_nfe_terceiro, to: 'nota_fiscais#download_nfe_terceiro'
    end
  end

  get "home/index"
  get "home/minor"

  root to: 'home#index'

end

app/models/dominio.rb
class Dominio < ActiveRecord::Base
  # has_many :dominio_valores
  has_many :dominio_valores, foreign_key: :dominio_id, class_name: DominioValor, :dependent => :destroy
  has_many :dominio_campos, foreign_key: :dominio_id, class_name: DominioCampo, :dependent => :destroy
  accepts_nested_attributes_for :dominio_valores, :dominio_campos, :allow_destroy => true

  validates :descricao, presence: true

  UNRANSACKABLE_ATTRIBUTES = ["created_at","updated_at"]

  def self.ransackable_attributes auth_object = nil
    (column_names - UNRANSACKABLE_ATTRIBUTES) + _ransackers.keys
  end

end

app/controllers/dominios_controller.rb
class DominiosController < ApplicationController
  before_action :set_dominio, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /dominios
  # GET /dominios.json
  def index
    @search = Dominio.search(params[:q])
    if params[:q].nil?
      #  @nota_fiscais = NotaFiscal.order("dtEmissaoNfe").limit(10)
      @dominios = Dominio.order("id")
     else
      @dominios = @search.result
    end
    @search.build_condition if @search.conditions.empty?
    @search.build_sort if @search.sorts.empty?
    authorize @dominios
  end

  # GET /dominios/1
  # GET /dominios/1.json
  def show
    @dominio_valores = DominioValor.where("dominio_id = " + params[:id].to_s)
    @dominio_campos = DominioCampo.where("dominio_id = " + params[:id].to_s)
  end

  # GET /dominios/new
  def new
    @dominio = Dominio.new
    authorize @dominio
  end

  # GET /dominios/1/edit
  def edit
    authorize @dominio
  end

  # POST /dominios
  # POST /dominios.json
  def create
    @dominio = Dominio.new(dominio_params)
    respond_to do |format|
      if @dominio.save
        format.html { redirect_to @dominio, notice: 'Dominio was successfully created.' }
        format.json { render action: 'show', status: :created, location: @dominio }
      else
        format.html { render action: 'new' }
        format.json { render json: @dominio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dominios/1
  # PATCH/PUT /dominios/1.json
  def update
    respond_to do |format|
      if @dominio.update(dominio_params)
        format.html { redirect_to @dominio, notice: 'Dominio was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @dominio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dominios/1
  # DELETE /dominios/1.json
  def destroy
    authorize @dominio
    respond_to do |format|
      format.html { redirect_to dominios_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dominio
      @dominio = Dominio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dominio_params
      params.require(:dominio).permit(:id, :descricao,
        dominio_valores_attributes: [:id, :codigo, :descricao, :_destroy],
        dominio_campos_attributes: [:id, :descricao, :_destroy])
    end
end

app/helpers/dominios_helper.rb
module DominiosHelper
end

app/views/dominios/_condition_fields.html.erb
<div class="field">
 <div class="row">
   <div class="control-group col-sm-3" style: "text-align: left;">
   <div class: "col-sm-4 control-label", style: "text-align: left;" >
     Campo
   </div>
   <div class="input-group date col-sm-4">
   <%= f.attribute_fields do |a| %>
     <%= a.attribute_select associations: [:category] %>
   <% end %>
   </div>
 </div>

  <div class="control-group col-sm-3" style: "text-align: left;">
   <div class: "col-sm-4 control-label", style: "text-align: left;" >
     Filtro
   </div>
   <div class="input-group date col-sm-4">
     <%= f.predicate_select only:[:gteq,:lteq,:eq,:cont]%>
   </div>
 </div>

 <div class="control-group col-sm-3" style: "text-align: left;">
   <div class: "col-sm-2 control-label", style: "text-align: left;" >
     Valor
   </div>
   <div class="input-group date col-sm-3">
   <%= f.value_fields do |v| %>
       <%= v.text_field :value %>
   <% end %>
   </div>
 </div>

 <div class="control-group col-sm-1" style: "text-align: left;">
   <div class: "col-sm-1 control-label", style: "text-align: left;" >
     &nbsp;
   </div>
   <div class="input-group date col-sm-1">
     <%= link_to "", '#', class: "remove_fields btn btn-xs label-danger fa fa-trash-o" %>
   </div>
 </div>
 </div>
</div>

app/views/dominios/_form.html.erb
<%- model_class = Dominio -%>
<%= nested_form_for(@dominio, html: { class: "form-horizontal", role: "form", name: "form"  }) do |f| %>
  <% if @dominio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dominio.errors.count, "error") %> prohibited this dominio from being saved:</h2>
      <ul>
      <% @dominio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="ibox-content">
      <form method="get" class="form-horizontal">
        <div class="form-group">
          <%= f.label :descricao, class: "col-md-2 control-label" %>
          <div class="col-md-10">
              <%= f.text_field :descricao, class: "form-control", required:true %>
          </div>
        </div>

        <div class="hr-line-dashed"></div>

        <div class="row">
          <div class="col-lg-12">
            <div class="panel blank-panel">
              <div class="panel-heading">
                <div class="panel-options">
                  <ul class="nav nav-tabs">
                    <li class="active"><a data-toggle="tab" href="#tab-1">Domínios Valores</a></li>
                     <li><a data-toggle="tab" href="#tab-2">Domínios Campos</a></li>
                  </ul>
                </div>
              </div>
              <div class="panel-body">
                <div class="tab-content">
                  <div id="tab-1" class="tab-pane active">
                      <table class="table table-bordered">
                        <thead>
                          <tr>
                            <th width="10%"><%= f.link_to_add "Adicionar", :dominio_valores, class: "btn btn-primary insert_in_table" %></th>
                            <th width="30%">Código</th>
                            <th width="60%">Descrição</th>
                          </tr>
                        </thead>
                        <tbody>
                          <%= f.fields_for :dominio_valores, :wrapper => false do|ff| %>
                            <tr class="fields">
                              <td><%= ff.link_to_remove "Excluir", :class => 'btn btn-white' %></td>
                              <td><%= ff.text_field :codigo , class: "form-control" %></td>
                              <td><%= ff.text_field :descricao , class: "form-control" %></td>
                            </tr>
                          <% end %>
                        </tbody>
                      </table>
                  </div>
                  <div id="tab-2" class="tab-pane">
                    <table class="table table-bordered">
                      <thead>
                        <tr>
                          <th width="10%"><%= f.link_to_add "Adicionar", :dominio_campos, class: "btn btn-primary insert_in_table" %></th>
                          <th width="90%">Descrição</th>
                        </tr>
                      </thead>
                      <tbody>
                        <%= f.fields_for :dominio_campos, :wrapper => false do |ff| %>
                          <tr class="fields">
                            <td><%= ff.link_to_remove "Excluir", :class => 'btn btn-white' %></td>
                            <td><%= ff.text_field :descricao , class: "form-control" %></td>
                          </tr>
                        <% end %>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="col-sm-4">
            <%= f.submit "Salvar", :class => 'btn btn-primary' %>
            <%= link_to 'Voltar', dominios_path, :class => 'btn btn-white' %>
          </div>
        </div>

      </form>
    </div>
  </div>
  </br>
<% end %>

<script type="text/javascript">
  $(document).ready(function(){
    window.NestedFormEvents.prototype.insertFields = function(content, assoc, link) {
      if($(link).hasClass('insert_in_table')){
        var $tr = $(link).closest('table').find('tbody').append(content);
        return $tr;
      }
      else{
        return $(content).insertBefore(link);
      }
    };
  });
</script>

app/views/dominios/edit.html.erb
<%- model_class = Dominio -%>
<h1>Editar Dominio</h1>
<%= render 'form' %>

app/views/dominios/index.html.erb
<%- model_class = Dominio -%>
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Dominios</h2>
        <ol class="breadcrumb">
            <li><a href="<%= url_for :controller => 'home', :action => 'index' %>">Home</a></li>
            <li class="active"><strong>dominios</strong></li>
        </ol>
    </div>
    <div class="col-lg-2"></div>
</div>
<p id="notice"><%= notice %></p>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <%= link_to new_dominio_path, class: 'btn btn-primary btn-xs' do %>
                        <span class="glyphicon glyphicon-plus"></span>
                        Novo
                    <% end %>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a href="#modal-form" data-toggle="modal" class="fa fa-wrench" ></a>

                        <div class="modal inmodal" id="modal-form" tabindex="-1" role="dialog" aria-hidden="true">
                            <div class="modal-dialog modal-lg">
                                <%= search_form_for @search, url: search_dominios_path, method: :post do |f| %>
                                <div class="modal-content animated bounceInRight">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                        <h4 class="modal-title">Pesquisa</h4>
                                    </div>
                                    <div class="modal-body">
                                        <%= f.condition_fields do |c| %>
                                            <%= render "condition_fields", f: c %>
                                        <% end %>
                                        <p><%= link_to_add_fields "Adicionar condições", f, :condition %></p>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Fechar</button>
                                        <%= f.submit "Procurar", class: "btn btn-primary" %>
                                    </div>
                                </div>
                                <% end %>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="ibox-content">
                    <table class="table table-striped table-bordered table-hover Tabela" >
                        <thead>
                            <tr>
                                <th width="05%">&nbsp</th>
                                <th width="05%">&nbsp</th>
                                <th width="05%">&nbsp</th>
                                                                <th><%=  model_class.human_attribute_name(:Descricao) %></th>
                                                            </tr>
                        </thead>
                        <tbody>
                            <%= content_tag_for(:tr, @dominios) do |dominio| %>
                            <td><%= link_to '', dominio, class: "btn btn-xs fa fa-search"%></td>
                            <td><%= link_to '', edit_dominio_path(dominio), class: "btn btn-xs fa fa-paste" %></td>
                            <td><%= link_to '', dominio, class: "btn btn-xs fa fa-times", method: :delete, data: { confirm: 'Confirma Exclusão ?' } %></td>
                                                        <td><%= dominio.descricao %></td>
                                                        <% end %>
                        </tbody>
                        <!-- <tfoot>
                            <tr>
                                <th>&nbsp</th>
                                <th>&nbsp</th>
                                <th>&nbsp</th>
                                                                <th>Descricao</th>
                                                            </tr>
                        </tfoot> -->
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


<% content_for :javascript do %>
<script type="text/javascript">
    $(function() {

      $('.Tabela').dataTable({
        "dom": 'T<"clear">lfrtip',
        "aoColumnDefs": [
              { 'bSortable': false, 'aTargets': [ 0,1,2 ] }
           ],
        "tableTools": {
            "sSwfPath": "../assets/dataTables/swf/copy_csv_xls_pdf.swf"
        }
    });
  });
</script>

<% end %>

app/views/dominios/new.html.erb
<%- model_class = Dominio -%>
<h1>Novo Dominio</h1>
<%= render 'form' %>

app/views/dominios/show.html.erb
<%- model_class = Dominio -%>
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-content">
                <p id="notice"><%= notice %></p>
                <form class="form-horizontal">
                    <div class="form-group">
                        <div class="col-md-2 control-label">
                             <%= model_class.human_attribute_name(:descricao) %>:
                        </div>
                        <div class="col-md-10">
                            <label class="form-control">
                                <%= @dominio.descricao %>
                            </label>
                        </div>

                        <div class="row">
                          <div class="col-lg-12">
                            <div class="panel blank-panel">
                              <div class="panel-heading">
                                <div class="panel-options">
                                  <ul class="nav nav-tabs">
                                    <li class="active"><a data-toggle="tab" href="#tab-1">Dominios Valores</a></li>
                                     <li><a data-toggle="tab" href="#tab-2">Dominios Campos</a></li>
                                  </ul>
                                </div>
                              </div>
                              <div class="panel-body">
                                <div class="tab-content">
                                  <div id="tab-1" class="tab-pane active">
                                      <table class="table table-bordered">
                                        <thead>
                                          <tr>
                                            <th width="30%">Código</th>
                                            <th width="70%">Descrição</th>
                                          </tr>
                                        </thead>
                                        <tbody>
                                          <% @dominio_valores.each do |dv| %>
                                            <tr class="fields">
                                              <td><%= dv.codigo %></td>
                                              <td><%= dv.descricao %></td>
                                            </tr>
                                          <% end %>
                                        </tbody>
                                      </table>
                                  </div>
                                  <div id="tab-2" class="tab-pane">
                                    <table class="table table-bordered">
                                      <thead>
                                        <tr>
                                          <th width="100%">Descrição</th>
                                        </tr>
                                      </thead>
                                      <tbody>
                                        <% @dominio_campos.each do |dc| %>
                                          <tr class="fields">
                                            <td><%= dc.descricao %></td>
                                          </tr>
                                        <% end %>
                                      </tbody>
                                    </table>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>


                    </div>
                    <div class="hr-line-dashed"></div>

                    <div class="form-group">
                    <div class="col-sm-4">
                        <%= link_to edit_dominio_path(@dominio), class: 'btn btn-primary' do %>
                        Editar
                        <% end %>
                        <%= link_to 'Voltar', dominios_path, :class => 'btn btn-white' %>
                        <%= link_to 'Novo', new_dominio_path, :class => 'btn btn-warning' %>
                    </div>
                </div>

                </form>

            </div>
        </div>
    </div>
</div>