config/routes.rb
NfeSws::Application.routes.draw do

  resources :crons do
    collection do
      post :search, to: 'crons#index'
      get 'download_xml_retorno'
    end
  end

  resources :usuario_empresas

  devise_for :users

  resources :control_users, only: [:index, :edit, :update, :show, :destroy], as: :users

  resources :empresas do
    collection { post :search, to: 'empresas#index' }
  end

  resources :dominio_campos do
    collection { post :search, to: 'dominio_campos#index' }
  end

  resources :dominio_valores do
    collection { post :search, to: 'dominio_valores#index' }
  end

  resources :dominios do
    collection { post :search, to: 'dominios#index' }
  end

  resources :nota_duplicatas do
    collection { post :search, to: 'nota_duplicatas#index' }
  end

  resources :nota_produtos do
    collection { post :search, to: 'nota_produtos#index' }
  end

  resources :nota_fiscais do
    collection do
      post :search, to: 'nota_fiscais#index'
      post 'manifestacao_destinatario'
      get 'download_xml_nfe_sefaz'
      get 'download_xml_nfe'
      get 'download_danfe_nfe'
      post 'negar_nfe'
      get :report, to: 'nota_fiscais#report_notas_fiscais'
      post :report, to: 'nota_fiscais#report_notas_fiscais'
      post :importar_nfe_xml, to: 'nota_fiscais#importar_nfe_xml'
      get :citacoes, to: 'nota_fiscais#citacoes'
      get :search_citacoes, to: 'nota_fiscais#citacoes'
      post :download_nfe_terceiro, to: 'nota_fiscais#download_nfe_terceiro'
    end
  end

  get "home/index"
  get "home/minor"

  root to: 'home#index'

end

app/models/nota_duplicata.rb
class NotaDuplicata < ActiveRecord::Base
  belongs_to :notaFiscal
end

app/controllers/nota_duplicatas_controller.rb
class NotaDuplicatasController < ApplicationController
  before_action :set_nota_duplicata, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /nota_duplicatas
  # GET /nota_duplicatas.json

  def index
    @search = NotaDuplicata.search(params[:q])
    if params[:q].nil?
       @nota_duplicatas = NotaDuplicata.order("dtVencimento").limit(10)
     else
      @nota_duplicatas = @search.result
    end
    @search.build_condition if @search.conditions.empty?
    @search.build_sort if @search.sorts.empty?
  end

  # GET /nota_duplicatas/1
  # GET /nota_duplicatas/1.json
  def show
  end

  # GET /nota_duplicatas/new
  def new
    @nota_duplicata = NotaDuplicata.new
  end

  # GET /nota_duplicatas/1/edit
  def edit
  end

  # POST /nota_duplicatas
  # POST /nota_duplicatas.json
  def create
    @nota_duplicata = NotaDuplicata.new(nota_duplicata_params)

    respond_to do |format|
      if @nota_duplicata.save
        format.html { redirect_to @nota_duplicata, notice: 'Nota duplicata was successfully created.' }
        format.json { render action: 'show', status: :created, location: @nota_duplicata }
      else
        format.html { render action: 'new' }
        format.json { render json: @nota_duplicata.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nota_duplicatas/1
  # PATCH/PUT /nota_duplicatas/1.json
  def update
    respond_to do |format|
      if @nota_duplicata.update(nota_duplicata_params)
        format.html { redirect_to @nota_duplicata, notice: 'Nota duplicata was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @nota_duplicata.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nota_duplicatas/1
  # DELETE /nota_duplicatas/1.json
  def destroy
    @nota_duplicata.destroy
    respond_to do |format|
      format.html { redirect_to nota_duplicatas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nota_duplicata
      @nota_duplicata = NotaDuplicata.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nota_duplicata_params
      params.require(:nota_duplicata).permit(:nrDuplicata, :dtVencimento, :valorDuplicata, :notaFiscal_id)
    end
end

app/helpers/nota_duplicatas_helper.rb
module NotaDuplicatasHelper
end

app/views/nota_duplicatas/_condition_fields.html.erb
<div class="field">
  <%= f.attribute_fields do |a| %>
    <%= a.attribute_select associations: [:category] %>
  <% end %>
  <%= f.predicate_select %>
  <%= f.value_fields do |v| %>
    <%= v.text_field :value %>
  <% end %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</div>

app/views/nota_duplicatas/_form.html.erb
<%= form_for(@nota_duplicata) do |f| %>
  <% if @nota_duplicata.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@nota_duplicata.errors.count, "error") %> prohibited this nota_duplicata from being saved:</h2>

      <ul>
      <% @nota_duplicata.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nrDuplicata %><br>
    <%= f.text_field :nrDuplicata %>
  </div>
  <div class="field">
    <%= f.label :dtVencimento %><br>
    <%= f.date_select :dtVencimento %>
  </div>
  <div class="field">
    <%= f.label :valorDuplicata %><br>
    <%= f.text_field :valorDuplicata %>
  </div>
  <div class="field">
    <%= f.label :notaFiscal_id %><br>
    <%= f.text_field :notaFiscal_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nota_duplicatas/edit.html.erb
<%- model_class = NotaDuplicata -%>
<h1>Editar NotaDuplicata</h1>
<%= render 'form' %>

app/views/nota_duplicatas/index.html.erb
<%- model_class = NotaDuplicata -%>
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>nota_duplicatas</h2>
        <ol class="breadcrumb">
            <li><a href="<%= url_for :controller => 'home', :action => 'index' %>">Home</a></li>
            <li class="active"><strong>nota_duplicatas</strong></li>
        </ol>
    </div>
    <div class="col-lg-2"></div>
</div>
<p id="notice"><%= notice %></p>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <%= link_to new_nota_duplicata_path, class: 'btn btn-primary btn-xs' do %>
                        <span class="glyphicon glyphicon-plus"></span>
                        Novo
                    <% end %>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a href="#modal-form" data-toggle="modal" class="fa fa-wrench" ></a>

                        <div class="modal inmodal" id="modal-form" tabindex="-1" role="dialog" aria-hidden="true">
                            <div class="modal-dialog">
                                <%= search_form_for @search, url: search_nota_duplicatas_path, method: :post do |f| %>
                                <div class="modal-content animated bounceInRight">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                        <h4 class="modal-title">Pesquisa</h4>
                                    </div>
                                    <div class="modal-body">
                                        <%= f.condition_fields do |c| %>
                                            <%= render "condition_fields", f: c %>
                                        <% end %>
                                        <p><%= link_to_add_fields "Adicionar condições", f, :condition %></p>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Fechar</button>
                                        <%= f.submit "Procurar", class: "btn btn-primary" %>
                                    </div>
                                </div>
                                <% end %>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="ibox-content">
                    <table class="table table-striped table-bordered table-hover Tabela" >
                        <thead>
                            <tr>
                                <th width="05%">&nbsp</th>
                                <th width="05%">&nbsp</th>
                                <th width="05%">&nbsp</th>
                                                                <th>Nrduplicata</th>
                                                                <th>Dtvencimento</th>
                                                                <th>Valorduplicata</th>
                                                                <th>Notafiscal</th>
                                                            </tr>
                        </thead>
                        <tbody>
                            <%= content_tag_for(:tr, @nota_duplicatas) do |nota_duplicata| %>
                            <td><%= link_to '', nota_duplicata, class: "btn btn-xs fa fa-search"%></td>
                            <td><%= link_to '', edit_nota_duplicata_path(nota_duplicata), class: "btn btn-xs fa fa-paste" %></td>
                            <td><%= link_to '', nota_duplicata, class: "btn btn-xs fa fa-times", method: :delete, data: { confirm: 'Confirma Exclusão ?' } %></td>
                                                        <td><%= nota_duplicata.nrDuplicata %></td>
                                                        <td><%= nota_duplicata.dtVencimento %></td>
                                                        <td><%= nota_duplicata.valorDuplicata %></td>
                                                        <td><%= nota_duplicata.notaFiscal %></td>
                                                        <% end %>
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>&nbsp</th>
                                <th>&nbsp</th>
                                <th>&nbsp</th>
                                                                <th>Nrduplicata</th>
                                                                <th>Dtvencimento</th>
                                                                <th>Valorduplicata</th>
                                                                <th>Notafiscal</th>
                                                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<!--
<% content_for :javascript do %>
<script type="text/javascript">
    $(function() {

      $('.Tabela').dataTable({
        "dom": 'T<"clear">lfrtip',
        "aoColumnDefs": [
              { 'bSortable': false, 'aTargets': [ 0,1,2 ] }
           ],
        "tableTools": {
            "sSwfPath": "../assets/dataTables/swf/copy_csv_xls_pdf.swf"
        }
    });
  });
</script>

<% end %>

-->

app/views/nota_duplicatas/new.html.erb
<%- model_class = NotaDuplicata -%>
<h1>Novo NotaDuplicata</h1>
<%= render 'form' %>

app/views/nota_duplicatas/show.html.erb
<%- model_class = NotaDuplicata -%>
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-content">
                <p id="notice"><%= notice %></p>
                <form class="form-horizontal">
                    <div class="form-group">
                        <div class="col-md-2 control-label">
                             <%= model_class.human_attribute_name(:nrDuplicata) %>:
                        </div>
                        <div class="col-md-10">
                            <label class="form-control">
                                <%= @nota_duplicata.nrDuplicata %>
                            </label>
                        </div>
                    </div>
                    <div class="hr-line-dashed"></div>

                                    <div class="form-group">
                        <div class="col-md-2 control-label">
                             <%= model_class.human_attribute_name(:dtVencimento) %>:
                        </div>
                        <div class="col-md-10">
                            <label class="form-control">
                                <%= @nota_duplicata.dtVencimento %>
                            </label>
                        </div>
                    </div>
                    <div class="hr-line-dashed"></div>

                                    <div class="form-group">
                        <div class="col-md-2 control-label">
                             <%= model_class.human_attribute_name(:valorDuplicata) %>:
                        </div>
                        <div class="col-md-10">
                            <label class="form-control">
                                <%= @nota_duplicata.valorDuplicata %>
                            </label>
                        </div>
                    </div>
                    <div class="hr-line-dashed"></div>

                                    <div class="form-group">
                        <div class="col-md-2 control-label">
                             <%= model_class.human_attribute_name(:notaFiscal) %>:
                        </div>
                        <div class="col-md-10">
                            <label class="form-control">
                                <%= @nota_duplicata.notaFiscal %>
                            </label>
                        </div>
                    </div>
                    <div class="hr-line-dashed"></div>

                                <div class="form-group">
                    <div class="col-sm-4">
                        <%= link_to edit_nota_duplicata_path(@nota_duplicata), class: 'btn btn-primary' do %>
                        Editar
                        <% end %>
                        <%= link_to 'Voltar', nota_duplicatas_path, :class => 'btn btn-white' %>
                    </div>
                </div>

                </form>

            </div>
        </div>
    </div>
</div>